name: Deploy
on:
  push:
    branches:    
      - prod

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        #GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        #GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        #OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        envkey_TEST: ${{ secrets.TEST }}
    - name: echo test command
        run: |
          echo .env.local.example
          echo .env
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          ls -al